services:
  mariadb:
    image: mariadb:latest
    container_name: dj-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --max-connections=1000 --innodb-snapshot-isolation=OFF
    ports:
      - "13306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  domserver:
    image: domjudge/domserver:latest
    container_name: domserver
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
      WEBAPP_BASEURL: ${WEBAPP_BASEURL}
    ports:
      - "80:80"
    volumes:
      - domserver_data:/opt/domjudge/domserver

volumes:
  mariadb_data:
  domserver_data: